### ISSUE TITLE
Is it possible to recognise regex in bash conditional contexts?

### ISSUE THREAD

**Issue by beingmrkenny** [Alhadis/language-regexp#5]
For example:

````
if [[ "$firstLine" =~ ^\[[A-Za-z]+-[0-9]+\][[:space:]]+(.*) ]]; then
	blurb=${BASH_REMATCH[1]};
fi
````

Currently the regex there isn't highlighted.

**Comment by Alhadis** [comment]
No, it's not (entirely) possible. Under normal circumstances, it *would* be; however, Atom now uses this annoying hybrid system where two partly-incompatible parsers are used to highlight source-code. Without going into specifics, there's a feature that both systems have that normally enables me to inject highlighting into unrelated grammars (that is, targeting files that aren't using the `Regular Expression` or `Regular Expression (Extended)` grammars). Since Atom introduced its new parsing system, however, that's no longer been an option.

I've added an injection for this, but you'll only see it if you disable Tree Sitter parsers:

> ![Figure 1](https://user-images.githubusercontent.com/2346707/80954699-3ca9c980-8e41-11ea-8e8d-198a4f50f355.png)  
> (Under **Settings** → **Core** → Scroll to the bottom → Uncheck **Use Tree Sitter Parsers**)

😞 I apologise for the long-winded explanation, but there was no simple "yes/no" answer I could give that was completely accurate/honest.

**EDIT:** I should add that you may have to disable `grammar-selector.hideDuplicateTextMateGrammars` in order to select “legacy” grammars in the grammar selector:

> ![Figure 2](https://user-images.githubusercontent.com/2346707/80957149-f440da80-8e45-11ea-854c-80d8546097a7.png)  
> (Found under **Settings** → **Packages** → Search for `grammar-selector` → **Settings** button)

**Comment by beingmrkenny** [comment]
Hey thanks for the detailed explanation! Can't tell you how many times the railroad diagram has found an error that would otherwise go unnoticed, so thanks :)
